// Generated by `pnpm --filter web run generate:importmap`. Regenerate after
// adding custom admin components; TanStack Start has no Next.js
// `app/(payload)/admin` folder for the Payload CLI to discover on its own, so
// `payload.config.ts` points `admin.importMap.importMapFile` at this file
// explicitly (see payload.config.ts).

/** @type import('payload').ImportMap */
export const importMap = {};
